dist: trusty

# Travis builds are slower using sudo: false (the container-based
# infrastructure) as of March 2017; see
# https://github.com/coq/coq/pull/467 for some discussion.
sudo: required
# Until Ocaml becomes a language, we set a known one.
language: c

cache:
  apt: true
  directories:
  - $HOME/.opam

before_cache:
  - rm -rf $HOME/.opam/log/

addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib
    - libtool
    - libglib2.0-dev
    - gobject-introspection
    - libgmp3-dev
    - nettle-dev
    - asciidoc
    - glib-networking
    - openssl
    - libcurl4-openssl-dev
    - libssl-dev

env:
  global:
  - NJOBS=2
  # system is == 4.02.3
  - COMPILER="system"
  - CAMLP5_VER="6.14"
  - PREFIX="-local"
  - USEMEGA="true"
  # Not ready yet for 8.7
  # - TEST_TARGET="ci-cpdt"
  # - TEST_TARGET="ci-metacoq"
  # - TEST_TARGET="ci-tlc"

matrix:

  # allow_failures:
  # - script: ./.travis.sh "ci-geocoq"

  include:
    - script: ./.travis.sh
      env:
      - TEST_TARGET="install"
      stage: build
      after_script: ./.travis-put.sh
    # - script: travis_wait ./.travis.sh "validate"
    #   env:
    #   - USEMEGA="false"
    #   stage: test
    # - script: ./.travis.sh "test-suite"
    #   env: COMPILER="4.02.3+32bit"
    #   env:
    #   - USEMEGA="false"
    #   stage: test
    # - script: travis_wait ./.travis.sh "validate"
    #   env: COMPILER="4.02.3+32bit"
    #   env:
    #   - USEMEGA="false"
    #   stage: test
    # - script: ./.travis.sh "ci-bedrock-src"
    #   stage: test
    # - script: ./.travis.sh "ci-coquelicot"
    #   stage: test
    # - script: ./.travis.sh "ci-geocoq"
    #   stage: test
    # - script: ./.travis.sh "ci-fiat-crypto"
    #   stage: test
    # - script: ./.travis.sh "ci-fiat-parsers"
    #   stage: test
    # - script: ./.travis.sh "ci-flocq"
    #   stage: test
    # - script: ./.travis.sh "ci-formal-topology"
    #   stage: test
    # - script: ./.travis.sh "ci-hott"
    #   stage: test
    # - script: ./.travis.sh "ci-iris-coq"
    #   stage: test
    # - script: ./.travis.sh "ci-math-classes"
    #   stage: test
    # - script: ./.travis.sh "ci-math-comp"
    #   stage: test
    - script: ./.travis.sh
      env:
      - TEST_TARGET="ci-sf"
      stage: test
    # - script: ./.travis.sh "ci-unimath"
    #   stage: test
    # - script: ./.travis.sh "ci-vst"
    #   stage: test


    # - stage: test
    #   script: ./.travis.sh "test-suite"
    #   env:
    #   - USEMEGA="false"
    #   - EXTRA_CONF="-coqide opt -with-doc yes"
    #   - EXTRA_OPAM="lablgtk-extras hevea"
    #   addons:
    #     apt:
    #       sources:
    #       - avsm
    #       packages: &extra-packages
    #       - opam
    #       - aspcud
    #       - libgtk2.0-dev
    #       - libgtksourceview2.0-dev
    #       - texlive-latex-base
    #       - texlive-latex-recommended
    #       - texlive-latex-extra
    #       - texlive-math-extra
    #       - texlive-fonts-recommended
    #       - texlive-fonts-extra
    #       - latex-xcolor
    #       - ghostscript
    #       - transfig
    #       - imagemagick

    # - stage: test
    #   script: ./.travis.sh "test-suite"
    #   env:
    #   - USEMEGA="false"
    #   - COMPILER="4.04.1"
    #   - CAMLP5_VER="6.17"
    #   - EXTRA_CONF="-coqide opt -with-doc yes"
    #   - EXTRA_OPAM="lablgtk-extras hevea"
    #   addons:
    #     apt:
    #       sources:
    #       - avsm
    #       packages: *extra-packages

    # - stage: test
    #   script: ./.travis.sh "coqocaml"
    #   env:
    #   - USEMEGA="false"
    #   - EXTRA_CONF="-coqide opt -warn-error"
    #   - EXTRA_OPAM="lablgtk-extras hevea"
    #   # dummy target
    #   - BUILD_TARGET="clean"
    #   addons:
    #     apt:
    #       sources:
    #       - avsm
    #       packages: &coqide-packages
    #       - opam
    #       - aspcud
    #       - libgtk2.0-dev
    #       - libgtksourceview2.0-dev

    # - stage: test
    #   script: ./.travis.sh "coqocaml"
    #   env:
    #   - USEMEGA="false"
    #   - COMPILER="4.04.1"
    #   - CAMLP5_VER="6.17"
    #   - EXTRA_CONF="-coqide opt -warn-error"
    #   - EXTRA_OPAM="lablgtk-extras hevea"
    #   # dummy target
    #   - BUILD_TARGET="clean"
    #   addons:
    #     apt:
    #       sources:
    #       - avsm
    #       packages: *coqide-packages

install:
# TODO cache this or something
- wget http://megatools.megous.com/builds/megatools-1.9.97.tar.gz
- zcat megatools-1.9.97.tar.gz > megatools-1.9.97.tar
- tar -xf megatools-1.9.97.tar
- pushd megatools-1.9.97
- ./configure
- make
- sudo make install
- popd

- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- eval $(opam config env)
- opam config list
- opam install -j ${NJOBS} -y camlp5.${CAMLP5_VER} ocamlfind ${EXTRA_OPAM}
- opam list

#Testing Gitter webhook
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3cdabdec318214c7cd63
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
